-- v2 AlgorithmSettings: remove legacy columns, add tunable v2 fields + JSON matrices.
-- Single global row `default` is re-seeded with values matching `src/lib/algorithm/constants.ts`.

DROP TABLE IF EXISTS "AlgorithmSettings";

CREATE TABLE "AlgorithmSettings" (
    "id" TEXT NOT NULL,
    "maxAutarchyDays" JSONB,
    "pshTable" JSONB,
    "solarBagAlignmentUplift" JSONB,
    "driveHoursPerDay" JSONB,
    "dodDefaults" JSONB,
    "roundtripDefaults" JSONB,
    "cRateChargeMax" JSONB,
    "absorptionTailH" JSONB,
    "chargerTargetCRate" JSONB,
    "shoreBridgeReliefDays" JSONB,
    "alternatorBridgeStandingCredit" JSONB,
    "topUpCoverageStandingCapMult" JSONB,
    "peakFactor" JSONB,
    "batterySafetyFactor" DOUBLE PRECISION NOT NULL DEFAULT 1.25,
    "autarchyPshDerate" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    "autarchyMaxBridgeDays" DOUBLE PRECISION NOT NULL DEFAULT 7,
    "hardBridgeDays" DOUBLE PRECISION NOT NULL DEFAULT 1,
    "topUpCoverageCap" DOUBLE PRECISION NOT NULL DEFAULT 0.75,
    "topUpCoverageCapAtLowPsh" DOUBLE PRECISION NOT NULL DEFAULT 0.58,
    "topUpCoveragePshBandHigh" DOUBLE PRECISION NOT NULL DEFAULT 2.5,
    "topUpCoveragePshBandLow" DOUBLE PRECISION NOT NULL DEFAULT 0.8,
    "topUpCoveragePortableWeight" DOUBLE PRECISION NOT NULL DEFAULT 0.55,
    "topUpCoveragePortableCapBump" DOUBLE PRECISION NOT NULL DEFAULT 0.18,
    "topUpCoverageAbsMax" DOUBLE PRECISION NOT NULL DEFAULT 0.97,
    "shoreBatteryReliefAutarchyThresholdDays" DOUBLE PRECISION NOT NULL DEFAULT 2,
    "inverterEfficiency" DOUBLE PRECISION NOT NULL DEFAULT 0.9,
    "inverterStandbyW" DOUBLE PRECISION NOT NULL DEFAULT 10,
    "inverterStandbyHours" DOUBLE PRECISION NOT NULL DEFAULT 24,
    "alternatorContinuousLimitA" DOUBLE PRECISION NOT NULL DEFAULT 60,
    "boosterEfficiency" DOUBLE PRECISION NOT NULL DEFAULT 0.9,
    "chargerEfficiency" DOUBLE PRECISION NOT NULL DEFAULT 0.92,
    "solarSystemEfficiency" DOUBLE PRECISION NOT NULL DEFAULT 0.75,
    "wpPerM2Rigid" DOUBLE PRECISION NOT NULL DEFAULT 200,
    "wpPerM2Flexible" DOUBLE PRECISION NOT NULL DEFAULT 150,
    "roofUtilizationFactor" DOUBLE PRECISION NOT NULL DEFAULT 0.8,
    "solarBagUtilization" DOUBLE PRECISION NOT NULL DEFAULT 0.6,
    "voltageDropCritical" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    "voltageDropNormal" DOUBLE PRECISION NOT NULL DEFAULT 3.0,
    "copperResistivity" DOUBLE PRECISION NOT NULL DEFAULT 0.0178,
    "inverterClasses" TEXT NOT NULL DEFAULT '500,800,1000,1500,2000,2500,3000,5000',
    "chargerClasses" TEXT NOT NULL DEFAULT '10,20,30,50,60',
    "solarControllerClasses" TEXT NOT NULL DEFAULT '10,20,30,40,50,60,80,100',
    "cableSizes" TEXT NOT NULL DEFAULT '6,10,16,25,35,50,70,95,120',
    "minPreselectionScore" INTEGER NOT NULL DEFAULT 30,
    "productSelectionMode" TEXT NOT NULL DEFAULT 'algorithm',
    "reasonGenerationMode" TEXT NOT NULL DEFAULT 'algorithm',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "AlgorithmSettings_pkey" PRIMARY KEY ("id")
);

INSERT INTO "AlgorithmSettings" (
    "id",
    "maxAutarchyDays",
    "pshTable",
    "solarBagAlignmentUplift",
    "driveHoursPerDay",
    "dodDefaults",
    "roundtripDefaults",
    "cRateChargeMax",
    "absorptionTailH",
    "chargerTargetCRate",
    "shoreBridgeReliefDays",
    "alternatorBridgeStandingCredit",
    "topUpCoverageStandingCapMult",
    "peakFactor",
    "updatedAt"
) VALUES (
    'default',
    '{"weekend":{"battery_only":3,"solar_or_alt":5,"solar_and_alt":7},"week":{"battery_only":7,"solar_or_alt":10,"solar_and_alt":14},"extended":{"battery_only":14,"solar_or_alt":30,"solar_and_alt":45},"permanent":{"battery_only":21,"solar_or_alt":60,"solar_and_alt":90}}'::jsonb,
    '{"scandinavia":{"summer":4.5,"all_year":0.8,"winter":0.3},"germany":{"summer":5.0,"all_year":1.5,"winter":0.9},"southern":{"summer":6.0,"all_year":2.5,"winter":1.9},"eastern":{"summer":4.5,"all_year":1.0,"winter":0.6},"varies":{"summer":5.0,"all_year":1.5,"winter":0.9}}'::jsonb,
    '{"scandinavia":{"summer":1.15,"all_year":1.55,"winter":2.0},"germany":{"summer":1.15,"all_year":1.45,"winter":1.8},"southern":{"summer":1.08,"all_year":1.2,"winter":1.4},"eastern":{"summer":1.15,"all_year":1.5,"winter":1.9},"varies":{"summer":1.15,"all_year":1.45,"winter":1.75}}'::jsonb,
    '{"weekend":{"short":0.5,"medium":0.5,"long":0.5},"week":{"short":1.0,"medium":0.75,"long":0.5},"extended":{"short":1.5,"medium":1.0,"long":0.5},"permanent":{"short":0.5,"medium":0.5,"long":0.5}}'::jsonb,
    '{"lifepo4":0.85,"agm":0.5,"gel":0.5}'::jsonb,
    '{"lifepo4":0.95,"agm":0.83,"gel":0.8}'::jsonb,
    '{"lifepo4":0.5,"agm":0.2,"gel":0.15}'::jsonb,
    '{"lifepo4":0.5,"agm":2.0,"gel":2.5}'::jsonb,
    '{"occasional":0.125,"nightly":0.25,"nightly_fast":0.45,"full_time":0.25}'::jsonb,
    '{"never":0,"occasional":0.75,"nightly":1,"nightly_fast":1.25,"full_time":2}'::jsonb,
    '{"short":1,"medium":0.82,"long":0.38}'::jsonb,
    '{"short":1,"medium":0.96,"long":0.9}'::jsonb,
    '{"low":1.25,"moderate":1.5,"high":2.0}'::jsonb,
    CURRENT_TIMESTAMP
);
